name: "Release Trigger"

on:
  repository_dispatch:
    type: [release_trigger]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Release Name
      run: |
        echo ${{ github.event.client_payload.release_name }}
    - uses: actions/github-script@v1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: "${{ github.event.client_payload.release_name }}"
          })
