name: "Release Trigger"

on:
  repository_dispatch:
    type: [release_trigger]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: List Repo Name 
      run: |
        echo Hello_World
